In [1]:
import numpy as np  ## we can write any things at place of np

In [2]:
print(np.__version__)

1.21.2


# Single-dimension arrays, behave similar to row vectors

In [8]:
x = np.array([1,2,3,4,5])

In [14]:
x1 = np.array([6,7,8,9,0])

In [21]:
print('x=',x, type(x))

x= [1 2 3 4 5] <class 'numpy.ndarray'>


In [23]:
print('x1=', x1)

x1= [6 7 8 9 0]


In [24]:
print(np.shape(x))

(5,)


In [25]:
x2 = np.array([[6,7,8,9,0]]) ## if we put one more [] in place x1 and then we see the shape it show 1D

In [27]:
print(np.shape(x2))   ## it show 1D array which have 5 elements means 1 row & 5 coloumn

(1, 5)


In [29]:
print(np.shape(x1),np.shape(x2))  ## its a difference x1 is not dimension but x2 is 1D

(5,) (1, 5)


In [32]:
print(x2.shape,x1.shape)  ### x2.shape & x2.shape(x2) both are same function 
                     ## so we say that  x2.shape == x2.shape(x2)

(1, 5) (5,)


In [33]:
y = x + 5
print('y=',y)

y= [ 6  7  8  9 10]


In [34]:
z = x*2
print('z=',z)

z= [ 2  4  6  8 10]


In [36]:
w = z**2
print('w=',w)

w= [  4  16  36  64 100]


In [39]:
k = x2 + 5
print('k=',k)

k= [[11 12 13 14  5]]


# 3. Matrices: Two-dimensional arrays

In [40]:
A = np.array([
              [1,2,3,4],
              [4,5,6,6],
              [7,8,9,9]
            ])

In [42]:
print(A,A.shape)

[[1 2 3 4]
 [4 5 6 6]
 [7 8 9 9]] (3, 4)


In [43]:
c = A+10
print(c,c.shape)

[[11 12 13 14]
 [14 15 16 16]
 [17 18 19 19]] (3, 4)


In [46]:
print('')

D = A*3
print(D)


[[ 3  6  9 12]
 [12 15 18 18]
 [21 24 27 27]]


# Compatible operations for matrices and vectors

In [50]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
print(A,A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [56]:
x = np.array([1,2,3])
print(A,x)
print('\n')
print(A + x)  #### only one [] is present note it

[[1 2 3]
 [4 5 6]
 [7 8 9]] [1 2 3]


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [54]:
y = np.array([[1,2,3]])
print(A + y)             ## we see here x and y both are same

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [59]:
x1 = np.array([[1],[2],[3]]) ## here i made it coloumn vector
print(x1,x1.shape)
print(A  + x1)

[[1]
 [2]
 [3]] (3, 1)
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [62]:
x1 = np.array([[1],[2],[3]])
# We can write it in softicated manner
x1 = np.array([
               [1],
               [2],
               [3]
             ])

In [63]:
x = np.array([1,2,3])
y = np.array([1,2,3])

inner = np.dot(x,y)

In [64]:
print(inner) ## it is dot product

14


In [67]:
outer = np.outer(x,y)
print(outer) ## here R1 of x is multiply by 1 that is first element of y
            ## here R2 of x is multiply by 2 that is second element of y
            ## here R3 of x is multiply by 3 that is third element of y
             

[[1 2 3]
 [2 4 6]
 [3 6 9]]


# 5.Random matrices

In [71]:
A = np.random.rand(5,3)
print(A) ## here it produce 5 rows & 3 coloumn with random number,all elements belongs to 0 & 1

[[0.35858025 0.00125073 0.1761735 ]
 [0.95228383 0.49336385 0.4557996 ]
 [0.55310239 0.14422013 0.99809302]
 [0.41744825 0.54170695 0.13244892]
 [0.20711864 0.95621042 0.9637111 ]]


In [72]:
x = np.random.rand(5)
print(x,type(x),x.shape)

[0.48521855 0.77084473 0.36995097 0.69510689 0.91575651] <class 'numpy.ndarray'> (5,)


In [76]:
## for random integer
x = np.random.randint(1,100,(6,7)) ## we use this formate
                                    ##   x = np.random.randint(...,...,(...,...))
                                                               #range#   #size#
                                                                        
print(x,x.shape)

[[36 75 69 82 41 93 40]
 [77  4 33 17 71 26 58]
 [33 81 67 70 29 23 73]
 [85 94 65 61 64  1 60]
 [76 32 27  8 76 32 46]
 [85 15 67 81 19 53 97]] (6, 7)


In [80]:
x = np.random.randint(-1000,1000,(6,7))
print(x)

[[-563  435 -973 -966  104  420 -111]
 [-760  964 -380  126  745 -957  313]
 [ 297  -78   72 -566  168 -593  610]
 [-250  410  755  540 -695  219  368]
 [-512 -133  239 -912 -637 -541  643]
 [ 899 -349  632 -569  334 -984 -752]]


In [93]:
A = np.random.rand(5,3)
print(1000*A)

[[358.1479644  345.68479897 740.28572415]
 [835.12258406 129.18814233 849.32119389]
 [862.8770299  625.38092489 841.34477649]
 [977.94915972 985.58421387 942.16653247]
 [391.37036375 236.07642624 579.23736707]]


# 6. Reshaping matrices

In [95]:
x = np.random.rand(12)
print(x,type(x),x.shape)

[0.48766496 0.971786   0.32284072 0.31104435 0.6218953  0.83605551
 0.83961658 0.28592009 0.65618294 0.74312521 0.48400839 0.4386364 ] <class 'numpy.ndarray'> (12,)


In [99]:
# we want this 12 element of x to reshape in 3x4 matrix i.e, 3 rows & 4 coloumn
y = np.reshape(x,(3,4))
print(y)

[[0.48766496 0.971786   0.32284072 0.31104435]
 [0.6218953  0.83605551 0.83961658 0.28592009]
 [0.65618294 0.74312521 0.48400839 0.4386364 ]]


In [102]:
x = np.array([x])
print(x,x.shape)

[[[0.48766496 0.971786   0.32284072 0.31104435 0.6218953  0.83605551
   0.83961658 0.28592009 0.65618294 0.74312521 0.48400839 0.4386364 ]]] (1, 1, 12)


In [103]:
A = np.random.rand(5,3)
print(A, type(A),A.shape)

[[0.00418233 0.54061961 0.66217677]
 [0.27003536 0.1000317  0.18919434]
 [0.64242461 0.37623913 0.24218288]
 [0.2642251  0.79313755 0.94500054]
 [0.92135978 0.48103411 0.5366595 ]] <class 'numpy.ndarray'> (5, 3)


In [106]:
print('')

x = np.random.rand(5)
print(x)
print('')
y = np.reshape(x,(5,1))
print(y)


[0.34976496 0.05208791 0.29194809 0.88342957 0.9224149 ]

[[0.34976496]
 [0.05208791]
 [0.29194809]
 [0.88342957]
 [0.9224149 ]]


In [108]:
print(A + y)

[[0.35394729 0.89038457 1.01194173]
 [0.32212327 0.15211962 0.24128226]
 [0.93437271 0.66818723 0.53413098]
 [1.14765467 1.67656712 1.82843011]
 [1.84377469 1.40344901 1.4590744 ]]


# 7.Combining(or stacking) matrices

In [109]:
x = np.random.rand(3)
print(x)
y = np.random.rand(3)
print(x)

[0.90016931 0.27415014 0.42739486]
[0.90016931 0.27415014 0.42739486]


In [111]:
z = np.vstack((x,y)) # vstack means vertical stacking
print(z,z.shape)

[[0.90016931 0.27415014 0.42739486]
 [0.13961785 0.45993103 0.44906157]] (2, 3)


In [114]:
z = np.hstack((x,y))  # hstack means horizantal stacking
print(z,z.shape)

[0.90016931 0.27415014 0.42739486 0.13961785 0.45993103 0.44906157] (6,)


<b>Exercise:</b> Create two arrays of size 3x5 intialized with random integer drawn from(-100,100) and vertically & horizontally them

In [132]:
x1 = np.random.randint(-100,100,(3,5))
x2 = np.random.randint(-100,100,(3,5))

vx = np.vstack((x1,x2))
hx = np.hstack((x1,x2))
print(vx)
print('\n')
print(hx)

[[  45   33   81   50   35]
 [  -3   84   90   92   37]
 [ -55   -7    3  -52  -47]
 [  95   35  -68   28  -30]
 [  47 -100  -68  -88  -19]
 [ -62   35  -92  -48  -55]]


[[  45   33   81   50   35   95   35  -68   28  -30]
 [  -3   84   90   92   37   47 -100  -68  -88  -19]
 [ -55   -7    3  -52  -47  -62   35  -92  -48  -55]]


# 8.Dimension and shape of NumPy arrays

In [116]:
A = np.random.rand(5,3)
print(A.ndim)
print(A.shape)

2
(5, 3)


In [5]:
x = np.random.rand(5,3,10,25)
print(x.ndim)
print(x.shape)

4
(5, 3, 10, 25)


In [6]:
print(x)

[[[[6.61314727e-01 5.12773126e-01 4.38387496e-01 ... 9.38800160e-01
    8.99069615e-01 8.73960953e-01]
   [3.67326123e-01 6.27514447e-01 6.42216033e-01 ... 5.40231271e-01
    1.63140778e-01 7.77297621e-01]
   [4.04103990e-01 5.95715171e-01 3.16849003e-01 ... 7.18752061e-01
    4.90749066e-01 2.70389866e-01]
   ...
   [9.14475580e-02 3.79062321e-01 2.27620421e-01 ... 5.95498752e-01
    5.83828449e-01 2.03658472e-01]
   [2.08195939e-01 9.17772520e-02 3.34425656e-02 ... 6.50110746e-01
    3.02783030e-01 9.91244044e-02]
   [6.94076778e-01 3.67365145e-01 6.03630117e-01 ... 7.48416458e-02
    1.89376703e-01 3.64482121e-01]]

  [[4.62520350e-01 8.00184851e-01 7.50918509e-01 ... 9.63426586e-01
    3.69902031e-01 5.99991801e-01]
   [4.83283770e-01 4.97850722e-01 5.99315615e-01 ... 4.25532282e-01
    5.22241500e-01 3.45105240e-02]
   [6.81085312e-01 1.63247783e-01 5.43360074e-01 ... 7.55140908e-01
    3.17356638e-01 4.34051525e-01]
   ...
   [1.11154059e-01 4.49589198e-01 6.48495594e-02 ... 7.04

# 9.Special Matrices

In [9]:
x = np.array([[1,2,3,4]])
y = np.array(((1,2,3,4)))
print(x,type(x),x.shape)
print(y,type(y),y.shape)

[[1 2 3 4]] <class 'numpy.ndarray'> (1, 4)
[1 2 3 4] <class 'numpy.ndarray'> (4,)


In [11]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array(((1,2,3,4),(5,6,7,8)))
print(x,type(x),x.shape)
print(y,type(y),y.shape)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)


In [12]:
print(np.zeros((3,2),dtype=int))

[[0 0]
 [0 0]
 [0 0]]


In [19]:
zf = np.zeros((3,2)) ## if we not defined data type so it is automatic in float
print(zf)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
zi = np.zeros((3,2),dtype=int)
print(zi)

[[0 0]
 [0 0]
 [0 0]]


In [21]:
print(type(zf),type(zi),zf.dtype,zi.dtype) ## gere zf.dtype & zi.dtype is member of numpy not a comment

<class 'numpy.ndarray'> <class 'numpy.ndarray'> float64 int32


In [23]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(np.ones((5,6),dtype=int))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [45]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [3]:
import numpy as np

In [5]:
np.matrix(np.eye(6),int)

matrix([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1]])

In [34]:
x = list(range(9))
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [36]:
x = list(range(0,9,2))
print(x)

[0, 2, 4, 6, 8]


In [41]:
A =  np.arange(0,9,2)
print(A, A.ndim, A.shape, type(A), A.dtype)

[0 2 4 6 8] 1 (5,) <class 'numpy.ndarray'> int32


In [40]:
A = np.arange(9)
B = np.reshape(A,(3,3))
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<b>Exercise:</b>use np.arange() function to create an array of size 4x2 where the elements will start from 0 to 14 (with step size 2) in row major order

In [50]:
a = np.arange(0,15,2)
b = np.reshape(a,(4,2))
print(b)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


# 10.Nupy array operations: max, argmax, min, argmin, sort, arrgsort

In [51]:
# x = np.array([5,4,1,8,7,3,9,2,6])
x = np.random.randint(0,100,15)
print(x)

[20 55 48 39  5 16 74 80 24  2 22 61 51 39 33]


In [53]:
print(np.max(x))

80


In [55]:
print(np.argmax(x))  ## here argmax means index of maximum of number

7


In [56]:
print(np.min(x))
print(np.argmin(x))

2
9


In [57]:
print(np.sort(x))  ## np.sort() function arrange in asscending order
print(np.argsort(x))  ## in this it shows the index of each element

[ 2  5 16 20 22 24 33 39 39 48 51 55 61 74 80]
[ 9  4  5  0 10  8 14  3 13  2 12  1 11  6  7]


<b>Exercise:</b>Geenerate an 1D array with 20 element randomly initialized with the numbers in [0,15]. Create another 1D array with 20 elements randomly initialized with the number in [0,1].Sort A and apply the sorted indices on B

In [77]:
A = np.random.randint(0,15,20)


B = np.random.rand(20)
print(A,B)
ind = np.argsort(A)
print(ind)
print(np.argsort(B))

[ 9 10  3  9  1 14 10  2  3 13 10  3 10  3  1 11 14 10  8  1] [0.75811842 0.0079295  0.78657042 0.65527826 0.26133313 0.70378719
 0.2791531  0.15491662 0.9754756  0.2405856  0.48647391 0.34906386
 0.81880664 0.11998965 0.71676984 0.0612113  0.01392109 0.60746838
 0.44730376 0.11502221]
[19 14  4  7  2 13 11  8 18  0  3 10 12  1 17  6 15  9  5 16]
[ 1 16 15 19 13  7  9  4  6 11 18 10 17  3  5 14  0  2 12  8]


In [78]:
print(B)
B1 = B[ind]
print(B1)

[0.75811842 0.0079295  0.78657042 0.65527826 0.26133313 0.70378719
 0.2791531  0.15491662 0.9754756  0.2405856  0.48647391 0.34906386
 0.81880664 0.11998965 0.71676984 0.0612113  0.01392109 0.60746838
 0.44730376 0.11502221]
[0.11502221 0.71676984 0.26133313 0.15491662 0.78657042 0.11998965
 0.34906386 0.9754756  0.44730376 0.75811842 0.65527826 0.48647391
 0.81880664 0.0079295  0.60746838 0.2791531  0.0612113  0.2405856
 0.70378719 0.01392109]


In [80]:
temp = np.random.randint(1, 205, (5,5))
print(temp)

[[150  91 136  87 158]
 [109  16  42 202  61]
 [176  58 151 100 186]
 [175 149 197 145  13]
 [143 170  92 110  86]]


In [83]:
print(temp[3,4]) ## element of third row & fourth coloumn we can also do as print(temp[3][4])

13


In [88]:
print(temp[4][4])

86


In [90]:
print(temp[0,0])

150


<b>Exercise:</b>Geenerate an 1D array with 20 element randomly initialized with the numbers in [0,15]. Create another 1D array with 20 elements randomly initialized with the number in [0,1].Sort A and apply the sorted indices on B

<b>ANSWER</b> is following

In [131]:
A = np.random.randint(0,15,(3,4))
B = np.random.rand(3,4)

print(A,B)
ind = np.argsort(A)
print(np.sort(A), ind)

[[ 1 14 10 12]
 [11 11 10 11]
 [ 2  2 10 12]] [[0.47257139 0.22929844 0.24381897 0.00240265]
 [0.5307168  0.58276072 0.16945129 0.09362883]
 [0.72367988 0.88767477 0.96714363 0.67164305]]
[[ 1 10 12 14]
 [10 11 11 11]
 [ 2  2 10 12]] [[0 2 3 1]
 [2 0 1 3]
 [0 1 2 3]]


In [132]:
print(B)
B2 = B
B2[0,:] = B2[0,ind[0,:]]
B2[1,:] = B2[1,ind[1,:]]
B2[2,:] = B2[2,ind[2,:]]
print(B2)

[[0.47257139 0.22929844 0.24381897 0.00240265]
 [0.5307168  0.58276072 0.16945129 0.09362883]
 [0.72367988 0.88767477 0.96714363 0.67164305]]
[[0.47257139 0.24381897 0.00240265 0.22929844]
 [0.16945129 0.5307168  0.58276072 0.09362883]
 [0.72367988 0.88767477 0.96714363 0.67164305]]


In [100]:
## Colon operator
C = np.random.rand(10)
print(C)
print('')
## I want to collect value of 1st indices to 5th indices
print(C[1:5])

[0.52855997 0.51037833 0.80871425 0.85125891 0.71685717 0.11011226
 0.0425673  0.58651049 0.20273427 0.28011543]

[0.51037833 0.80871425 0.85125891 0.71685717]


In [102]:
print(C[0:5])

[0.52855997 0.51037833 0.80871425 0.85125891 0.71685717]


In [104]:
## I want to display from last TO UP TO 5 element
print(C[5:-1])

[0.11011226 0.0425673  0.58651049 0.20273427]


In [106]:
print(C[5:-4])

[0.11011226]


In [112]:
print(C[5:]) ## I want to include last then -ve part is not required

[0.11011226 0.0425673  0.58651049 0.20273427 0.28011543]


In [114]:
## if we not specify any thiny thing except [:] then it means all the elements
print(C[:])

[0.52855997 0.51037833 0.80871425 0.85125891 0.71685717 0.11011226
 0.0425673  0.58651049 0.20273427 0.28011543]


In [125]:
C = np.random.rand(3,5)
print(C)

[[0.62023886 0.2728045  0.46285066 0.25287983 0.4418367 ]
 [0.38021074 0.22251086 0.02429507 0.44754196 0.41329275]
 [0.7500436  0.96418746 0.38440044 0.5438151  0.68267954]]


In [127]:
## I WANT TO DISPLAY FROM 2ND COLOUMN TO 4TH COLOUMN AND UP TO 2ND ROW
print(C[1:3,1:4])

[[0.22251086 0.02429507 0.44754196]
 [0.96418746 0.38440044 0.5438151 ]]


In [129]:
print(C[1:3, :]) ## IF WE NOT SPECIFY THE COLOUMN THEN ALL COLOUMN WILL SHOW

[[0.38021074 0.22251086 0.02429507 0.44754196 0.41329275]
 [0.7500436  0.96418746 0.38440044 0.5438151  0.68267954]]


In [115]:
print(C[5:])
print(C[:])

[[0.75034744 0.46385455 0.0750665  0.32396706 0.27984754]
 [0.59438053 0.39955364 0.33385654 0.40440221 0.21782805]
 [0.62119248 0.3584205  0.38771718 0.96272451 0.85682968]]
[[0.59438053 0.39955364 0.33385654 0.40440221 0.21782805]
 [0.62119248 0.3584205  0.38771718 0.96272451 0.85682968]]
[]
[[0.75034744 0.46385455 0.0750665  0.32396706 0.27984754]
 [0.59438053 0.39955364 0.33385654 0.40440221 0.21782805]
 [0.62119248 0.3584205  0.38771718 0.96272451 0.85682968]]


# 11.Statistical operations: mean, var, std.....

In [135]:
x = np.array([5,4,1,8,7,3,9,2,6])

print(np.mean(x))
print(np.var(x))
print(np.std(x))


5.0
6.666666666666667
2.581988897471611


# 12.Boolean Element-Wise operations

In [136]:
x = np.random.rand(3,3)
print(x)

[[0.21509081 0.19342713 0.93589668]
 [0.19361768 0.11788665 0.81878875]
 [0.79213476 0.18968998 0.21598902]]


In [138]:
y = (x>0.5)
print(y,y.dtype)

[[False False  True]
 [False False  True]
 [ True False False]] bool


In [141]:
print(x[1,2])

0.8187887503956576


In [142]:
w = (x[1,2]>0.5)
print(w,w.dtype)

True bool


# 13.Boolean 'Mask'

In [150]:
x = np.random.rand(3,3)
print(x)

[[0.07389749 0.61540765 0.09215065]
 [0.94169724 0.5869599  0.84255935]
 [0.09944109 0.48202064 0.12423508]]


In [153]:
mask = x > 0.5
print(mask)

[[False  True False]
 [ True  True  True]
 [False False False]]


In [154]:
print(x[mask])

[0.61540765 0.94169724 0.5869599  0.84255935]


In [163]:
x[mask] = 0
print(x) ## here the True value become zero

[[0.34406418 0.         0.77495407]
 [0.         0.         0.        ]
 [0.23604757 0.19740188 0.26329135]]


In [159]:
y = np.random.rand(3,3)
print(y)

[[0.0125856  0.37572542 0.81262027]
 [0.9864855  0.37500218 0.13711357]
 [0.95973348 0.48343168 0.46614591]]


In [164]:
r, c = np.where(x==0) # r FOR ROW & c FOR COLOUMN
print(r,c)

[0 1 1 1] [1 0 1 2]


In [166]:
x = np.array([1,2,3,4,5])

def f(x):
    return x**2

for i in x:
    print(i,f(i))

1 1
2 4
3 9
4 16
5 25


In [3]:
x = np.array([
   [[2,1],
    [3,5]],
   [[0,1],
    [3,5]],
   [[1,2],
    [9,5]]
])

# Some important operations in NumPy

In [17]:
r2 = np.random.randint(1,10,(4,5))
print(r2)

[[7 5 3 7 4]
 [4 8 9 4 9]
 [5 2 6 7 4]
 [5 1 8 5 3]]


In [12]:
print(np.empty((4,5)))  ## all its output is garbeg

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 6.23054293e-307
  2.22526399e-307]
 [6.23053614e-307 7.56592338e-307 1.60216183e-306 7.56602523e-307
  3.56043054e-307]
 [1.37961641e-306 2.22518251e-306 1.33511969e-306 3.11525958e-307
  9.34593493e-307]
 [8.90104918e-307 1.69119602e-306 8.45606157e-307 1.42410974e-306
  2.22522596e-306]]


In [6]:
y = np.empty_like(r2)  ## here like function define the size only
print(y)

[[1011296453 1150021803 -529751619 -710496226          1]
 [   7536754 1903232307 1228390074 -608888445  919379183]
 [         1          0          0          0          1]
 [   7209071          0          0          1          3]]


In [27]:
y = np.zeros_like(r2)
print(y)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
y = np.ones_like(r2)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
y = np.empty_like(r2)
print(y)  ## here we shaw the GENERALLY empty_like() gives the  result like previous/just recently running cell

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [29]:
print(np.empty_like(r2))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [35]:
print(r2.T) ## Transpose
print('')
print(np.transpose(r2))  

## both are for transpose

[[7 4 5 5]
 [5 8 2 1]
 [3 9 6 8]
 [7 4 7 5]
 [4 9 4 3]]

[[7 4 5 5]
 [5 8 2 1]
 [3 9 6 8]
 [7 4 7 5]
 [4 9 4 3]]


In [37]:
x= np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [39]:
print(np.sum(x))  ## Compute sum of all elements; print "10"

10


In [41]:
x = np.random.randint(1,100,(5,6))
print(x)
print(np.sum(x))
print('')
print(x.sum()) ## here also inplace operation is present

[[73 17 41 81 27 85]
 [22 21  9 87 90 30]
 [27 20 95 54 14 69]
 [65 69 23 60 50 55]
 [ 7 35 83 77 90 26]]
1502

1502


In [43]:
print(np.sum(x, axis=0))  ## Compute sum of each coloumn: prints "[4,6]" ; (axis=0 means coloumn wise)

[194 162 251 359 271 265]


In [44]:
print(np.sum(x, axis=1))   ## Compute sum of each rows: prints "[3,7]"   ;  (axis=0 means coloumn wise)

[324 259 279 322 318]


In [47]:
print(np.sqrt(x)) ## it calculate the square root of each element in matrix x

[[8.54400375 4.12310563 6.40312424 9.         5.19615242 9.21954446]
 [4.69041576 4.58257569 3.         9.32737905 9.48683298 5.47722558]
 [5.19615242 4.47213595 9.74679434 7.34846923 3.74165739 8.30662386]
 [8.06225775 8.30662386 4.79583152 7.74596669 7.07106781 7.41619849]
 [2.64575131 5.91607978 9.11043358 8.77496439 9.48683298 5.09901951]]


In [49]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [51]:
print(np.add(x,y)) ## it perform element wise operation

[[ 6  8]
 [10 12]]


In [53]:
print(x+y) ## we cn also do this type

[[ 6  8]
 [10 12]]


In [54]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [56]:
print(np.add(x,y)) ## row wise addition done

[[ 6  8]
 [ 8 10]]


In [57]:
print(x+y)

[[ 6  8]
 [ 8 10]]


In [58]:
y = 20
print(x+y) ## here 20 is added in all element of x

[[21 22]
 [23 24]]


In [59]:
print(np.add(x,y))

[[21 22]
 [23 24]]


In [60]:
print(x*y)

print(x-y)
print(x/y)

[[20 40]
 [60 80]]
[[-19 -18]
 [-17 -16]]
[[0.05 0.1 ]
 [0.15 0.2 ]]


In [62]:
a2d = np.array([[1,2,3],[4,5,6]])
b2d = np.array([[10,4,6],[2,4,6]])
print(a2d, a2d.shape)
print(b2d, b2d.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[10  4  6]
 [ 2  4  6]] (2, 3)


In [66]:
print(b2d.shape)

(2, 3)


In [68]:
print(b2d.shape[0]) ##  if we place zero then it give no. of rows

2


In [69]:
print(b2d.shape[1]) ##  if we place zero then it give no. of rows

3


In [70]:
r, c = b2d.shape ## here we store the shape in two variable
print(r,c)

2 3


<b>Exercise:</b>Define a random matrix of shape 7x8. Fetch the number of rows and coloumns programattically. Then manipulate each element of the matrix with following formula: x = sqrt((x+5)/10), x refers to each element of the matri.

In [74]:
A = np.random.randint(1,50,(7,8))
print(A)
row, col = A.shape
print(row, col)
for i in range(row):
    for j in range(col):
        A[i,j] = np.sqrt((A[i,j]+5)/10)
print(A)
print('')
## WE CAN ALSO DO THIS IN FOLLOWING WAYS:
A = np.random.rand(7,8)
print(A)
row, col = A.shape
print(row, col)
for i in range(row):
    for j in range(col):
        A[i,j] = np.sqrt((A[i,j]+5)/10)
print(A)

[[17 14 29 37 45 11 41  7]
 [26 37 45 42 48 48 30  7]
 [27 15  4 25 24 23 20 18]
 [ 1 13 22 39 17 35  1 20]
 [ 3  2 41  9 44  2  5  4]
 [37 41 27 26 18 24 31 11]
 [35 15 39  1 41 34 41 38]]
7 8
[[1 1 1 2 2 1 2 1]
 [1 2 2 2 2 2 1 1]
 [1 1 0 1 1 1 1 1]
 [0 1 1 2 1 2 0 1]
 [0 0 2 1 2 0 1 0]
 [2 2 1 1 1 1 1 1]
 [2 1 2 0 2 1 2 2]]

[[0.50919024 0.12225309 0.07129237 0.32542598 0.99952328 0.90800124
  0.19976522 0.47064011]
 [0.80482798 0.1730563  0.26360585 0.63962189 0.53392526 0.09808219
  0.87880763 0.72023596]
 [0.02180239 0.53963094 0.57562934 0.33063954 0.57839731 0.08399428
  0.31303147 0.49257025]
 [0.44110309 0.03367748 0.5899445  0.71120944 0.74965628 0.2335253
  0.45610357 0.9225353 ]
 [0.70683697 0.67901802 0.38338624 0.66480615 0.59028506 0.28565833
  0.05052028 0.08299894]
 [0.04184022 0.52474277 0.57850546 0.91430579 0.37506444 0.29559046
  0.91231596 0.36038389]
 [0.17975056 0.91358723 0.32879769 0.31195747 0.63943506 0.57053796
  0.46184112 0.79448062]]
7 8
[[0.7422392  0.7

In [78]:
a2d = np.array([[1,2,3],[4,5,6]])
b2d = np.array([[10,4,6],[2,4,6]])
print(a2d, a2d.shape)
print(b2d, b2d.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[10  4  6]
 [ 2  4  6]] (2, 3)


In [79]:
c2d = a2d.T ## Transpose
print(c2d)
print(a2d)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [80]:
## belement wise multiplication
d2d = a2d * b2d
print(d2d)

[[10  8 18]
 [ 8 20 36]]


In [84]:
d_2d  = np.multiply(a2d,b2d) ## we can do same work with this function
print(d_2d)

[[10  8 18]
 [ 8 20 36]]


In [87]:
print(a2d.shape,b2d.shape,c2d.shape)

(2, 3) (2, 3) (3, 2)


In [90]:
## Mtrix Multiplication
e2d = np.dot(a2d,c2d)
print(e2d)
 

[[14 32]
 [32 77]]


In [94]:
e_2d = np.matmul(a2d,c2d) ## same matrix multiplication can be done by matmul function
print(e_2d)

[[14 32]
 [32 77]]


In [96]:
det1 = np.linalg.det(e2d) ## this function give the determinants of the function
print(det1)

54.00000000000001


In [97]:
eig, eig1 = np.linalg.eig(e2d)
print(eig)
print(eig1)

[ 0.59732747 90.40267253]
[[-0.92236578 -0.3863177 ]
 [ 0.3863177  -0.92236578]]


In [98]:
## for inverse of matrix
inv1 = np.linalg.inv(e2d)
print(inv1)

[[ 1.42592593 -0.59259259]
 [-0.59259259  0.25925926]]


In [99]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [101]:
b = a[:2, 1:3]  ## Last exclusive
print(b)  ### we extract a matric of 1st two row & from 1 to 3 coloumn(means 2nd & 3rd coloumn),where last exclusive

[[2 3]
 [6 7]]


In [104]:
b[0,0] = 77   ## i want to change b[0,0] location by 77
print(b)
print(a)

[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [106]:
b[0,1] = 64
print(b)

[[77 64]
 [ 6  7]]


In [107]:
print(a)

[[ 1 77 64  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
c = np.copy(a)
print(c)

[[ 1 77 64  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
c[0,0]= 105
print(c)
print(a)

[[105  77  64   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1 77 64  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
## we will add the vector v to each row of matrix x,
## storing the result in the matrix y
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
v = np.array([1,0,1])
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [116]:
vv = np.tile(v, (4,1))      ## stack 4 copies of v on top of each other one time
print(vv)                 ## prints "[[1,0,1]
                          ##         [1,0,1]
                          ##         [1,0,1]
                          ##         [1,0,1]]"
            

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [119]:
vv = np.tile(v, (4,2))      ## stack 4 copies of v on top of each other 2 time
print(vv)          ## here 4 copies tileing  twice

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [121]:
vv = np.tile(v, (3,5))      ## stack 3 copies of v on top of each other five time
print(vv)

[[1 0 1 1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 0 1 1 0 1 1 0 1]
 [1 0 1 1 0 1 1 0 1 1 0 1 1 0 1]]


In [123]:
print(x+v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [122]:
vv = np.tile(v, (4,1))      ## stack 4 copies of v on top of each other one time
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [124]:
y = x + vv     ## Add x and vv element wise
print(y)       ##prints     "[[2,2,4]
               ##             [5,5,7]
               ##             [8,8,10]
               ##             [11,11,13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [126]:
## we will add the vector v to each row of matrix x,
## storing the result in the matrix y
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

v = np.array([1,0,1])  
y = x+v ## Add v to each row of x using broadcasting
print(y)       ##prints     "[[2,2,4]
               ##             [5,5,7]
               ##             [8,8,10]
               ##             [11,11,13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<b>Exercise:</b> Create an random array A of size 5x4. Using np.tile() function, Add a random vector of size 4 with first three rows of A and at another random vector of size 4 with last two rows of A.

In [130]:
A = np.random.randint(1,100,(5,4))
vec1 = np.random.randint(0,2,4)
vec2 = np.random.randint(0,2,4)
print(A)
print(vec1)
print(vec2)

[[96 86 40 42]
 [86  9 23  4]
 [ 2 61 35 91]
 [ 2 21 25 94]
 [89 27 46 65]]
[1 1 1 1]
[0 1 1 1]


In [131]:
A[:3,:] = A[:3,:]+vec1
A[3:,:] = A[3:,:]+vec2
print(A)

[[97 87 41 43]
 [87 10 24  5]
 [ 3 62 36 92]
 [ 2 22 26 95]
 [89 28 47 66]]


# Reference
#### NumPy documentation
#### NumPy user guide